server:
  port: 8081

spring:
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /
    username: test1
    password: test1
    publisher-confirms: true #消息发送到交换器确认
    publisher-returns: true #消息发送到队列确认
